services:
  - type: web
    name: my-fastapi-app
    env: python
    buildCommand: |
      pip install -r requirements.txt && prisma generate && prisma py fetch
    startCommand: uvicorn api:app --host 0.0.0.0 --port 10000
